<?php

class Hashid_Core extends \Hashids\Hashids {
	protected static $instance = null;

	function __construct()
	{
		extract(Kohana::$config->load('hashid')->as_array());

		parent::__construct($salt, $min_hash_length, $alphabet); // TODO: Change the autogenerated stub
	}

	/**
	 * @param string $hash
	 *
	 * @return null|int
	 */
	function decrypt_one($hash)
	{
		$hash = $this->decrypt($hash);
		if (isset($hash[0]))
		{
			return $hash[0];
		}
		return null;
	}

	/**
	 * @return Hashid_Core
	 */
	static function instance()
	{
		if (!(self::$instance instanceof self))
		{
			self::$instance = new self();
		}
		return self::$instance;
	}
}
